[package]
name = "tetris-ai"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = "0.5.1"
pyo3 = { version = "0.23.2", features = ["auto-initialize"] }
rand = "0.8.5"

[[bench]]
name = "copy"
harness = false
