/** DO NOT EDIT! This file is generated by @svelte-put/inline-svg vite plugin */
declare module 'svelte/elements' {
	export interface SVGAttributes {
		'inline-src'?:
			| `./${string}`
			| `../${string}`
			| '.comments'
			| 'arrow-clockwise'
			| 'arrow-left'
			| 'arrow-return-left'
			| 'arrow-right'
			| 'list'
			| 'pause'
			| 'play'
			| 'shuffle'
			| 'stop'
			| 'translate'
			| 'trash'
			| 'x';
	}
}
export {};
