/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_move_free: (a: number, b: number) => void;
export const __wbg_get_move_rot: (a: number) => number;
export const __wbg_set_move_rot: (a: number, b: number) => void;
export const __wbg_get_move_row: (a: number) => number;
export const __wbg_set_move_row: (a: number, b: number) => void;
export const __wbg_get_move_col: (a: number) => number;
export const __wbg_set_move_col: (a: number, b: number) => void;
export const __wbg_piece_free: (a: number, b: number) => void;
export const __wbg_wasmpattern_free: (a: number, b: number) => void;
export const __wbg_get_wasmpattern_data: (a: number) => [number, number];
export const __wbg_set_wasmpattern_data: (a: number, b: number, c: number) => void;
export const get_piece_rotation: (a: number, b: number) => number;
export const __wbg_pattern_free: (a: number, b: number) => void;
export const __wbg_simulator_free: (a: number, b: number) => void;
export const __wbg_get_simulator_steps: (a: number) => bigint;
export const __wbg_set_simulator_steps: (a: number, b: bigint) => void;
export const __wbg_moveresult_free: (a: number, b: number) => void;
export const __wbg_get_moveresult_piece_idx: (a: number) => number;
export const __wbg_set_moveresult_piece_idx: (a: number, b: number) => void;
export const __wbg_get_moveresult_path: (a: number) => [number, number];
export const __wbg_set_moveresult_path: (a: number, b: number, c: number) => void;
export const simulator_new: () => number;
export const simulator_step: (a: number) => number;
export const simulator_board_data: (a: number) => [number, number];
export const simulator_generate_moves: (a: number, b: number) => [number, number];
export const wasm_test: () => [number, number, number];
export const __wbg_get_wasmpattern_size: (a: number) => number;
export const __wbg_set_wasmpattern_size: (a: number, b: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
